name = "MoBuilder"
uuid = "4d224c2a-e2ea-409b-a892-06935f8395c5"
authors = ["caoyuyu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
