[digit_dataset]
git-tree-sha1 = "8d33d9a5e642fdd4d2eac97e303159f1eea1ee9a"
lazy = true

    [[digit_dataset.download]]
    sha256 = "fb36f5d02753fa5f19be1ae88613f5a8ae3bab7c369aab107a76e3c288266fea"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/DigitDataset.tar.gz"

[imagenet]
git-tree-sha1 = "90cbc0422ebe3db039c0aab9d4c43423f8e1c9cd"
lazy = true

    [[imagenet.download]]
    sha256 = "cb5fdddb63ad60edaff223b64c33c554eba6f05405b4b7c752738c224525f814"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/imagenet.tar.gz"

[iris_dataset]
git-tree-sha1 = "9443891182059b853321150addf603be1dac6570"
lazy = true

    [[iris_dataset.download]]
    sha256 = "6d49d70f746543134631e4430e3ad3e6781cb3f41556bdf27fddc59ca06e1c21"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/iris_dataset.tar.gz"

[flights_dataset]
git-tree-sha1 = "f079560951f2c2e1a36c18d953937cb5130a4b51"
lazy = true

    [[flights_dataset.download]]
    sha256 = "458288a74ed41e3cd7b08b4f443f91a5ba1b7abec64eeeb134b4ba47b019847a"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/predictAndUpdateState_train_data.tar.gz"

[simplefit_dataset]
git-tree-sha1 = "77780bc1667b7dc4a978c73c63bfa84924c47ff6"
lazy = true

    [[simplefit_dataset.download]]
    sha256 = "2aa335ab337ad9ba1c077e794c0a4d0918742ef3d580b6d6c60784baec019d56"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/simplefit_dataset.tar.gz"

[VPR_dataset]
git-tree-sha1 = "731fa31a4a8e5c7b67bddc00ad04be30e39ad3c8"
lazy = true

    [[VPR_dataset.download]]
    sha256 = "2adeac179d06b8731dd8f76785ce4f9ffdb86b1dc7770715050bab1266aa0acd"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/VPR_dataset.tar.gz"

[abalone_dataset]
git-tree-sha1 = "c30e1bf3ec85a03f860e19e1a42d0d66c93465f8"
lazy = true

    [[abalone_dataset.download]]
    sha256 = "becf6346faf04d70d4180830944e420d1619821105e7897080e38e59e94bfaf9"
    url = "https://oss-dev.tongyuan.cc/syslab-assets/TyDeepLearning/abalone_dataset.tar.gz"
